seed: 1380
dataset: mnist
num_epochs: 100
save_every: 10
batch_size: 128

wandblog: False
aattack_version: pgd #apgd-ce 
unsupervised: True

loss: gairat_loss

mnist:
  learning_rate: 0.01
  opt_params:
    momentum: 0.9
  adv_test:
    epsilon: 0.3
    perturb_steps: 20
    step_size: 0.03
    norm: Linf
  loss_args:
    beta: 4
    epsilon: 0.3
    perturb_steps: 10
    step_size: 0.075 #eps/4
    norm: Linf
cifar10:
  learning_rate: 0.1
  opt_params:
    weight_decay: 0.0005
    momentum: 0.9
  adv_test:
    epsilon: 0.031
    perturb_steps: 20
    step_size: 0.0031
    norm: Linf
  loss_args:
    beta: 4
    epsilon: 0.031
    perturb_steps: 10
    step_size: 0.0078
    norm: Linf
cifar100:
  adv_test:
    epsilon: 0.031
    perturb_steps: 20
    step_size: 0.0031
    norm: Linf
